### Generated by rprotoc. DO NOT EDIT!
### <proto file: cache.proto>
# message GitRepoReference {
#         required string GitRepo = 1;
# }
# 
# message DiffReference {
# }
# 
# message CacheReference {
#     // The basic thought is that you can have one Diff, and one of any of the
#     // other repo sources, it's simple, but we can worry about expanding it
#     // if we can ever think of more complicated scenario's later.
#     optional DiffReference Diff = 1;
#     enum RepoType {
#         Repo_Git = 1;
#     }
#     required RepoType Repo = 2;
#     optional GitRepoReference Git = 3;
# }
require 'protobuf/message/message'
require 'protobuf/message/enum'
require 'protobuf/message/service'
require 'protobuf/message/extend'

class GitRepoReference < ::Protobuf::Message
  defined_in __FILE__
  required :string, :GitRepo, 1
end
class DiffReference < ::Protobuf::Message
  defined_in __FILE__
end
class CacheReference < ::Protobuf::Message
  defined_in __FILE__
  optional :DiffReference, :Diff, 1
  class RepoType < ::Protobuf::Enum
    defined_in __FILE__
    Repo_Git = value(:Repo_Git, 1)
  end
  required :RepoType, :Repo, 2
  optional :GitRepoReference, :Git, 3
end